name: flutter_task_01
description: flutter_task_01
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-89.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  cupertino_icons: ^1.0.2
  #carousel_slider: ^4.2.1
  carousel_slider:
    git:
      url: https://github.com/serenader2014/flutter_carousel_slider
      ref: null-safty
      path:
  import_sorter: ^4.6.0

#flutter pub run import_sorter:main -e
#pub run import_sorter:main -e if normal dart application
import_sorter:
  emojis: false # Optional, defaults to false
  comments: true # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/tests\/*

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.7.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
